### ISSUE TITLE
Doesn't adhere to global hotkey setting

### ISSUE THREAD

**Issue by Californ1a** [Dalet/LiveSplit.FocusedHotkeys#1]
It continues to utilize global hotkeys, when the selected process is focused, while global hotkeys are disabled. It should only enable when global hotkeys are enabled. When global hotkeys are disabled then it should act as if no processes are added in the layout settings.

Alternatively, a toggle option to "disable along with global hotkeys."

**Comment by Dalet** [comment]
This is intended. I made this so I could type while being alt-tabbed out of the game without accidentally activating hotkeys, the "Toggle Global Hotkeys" hotkey is one of them!
I could add a toggle button just below "Global Hotkeys" in the Control menu though.

**Comment by Californ1a** [comment]
It works perfectly for that use-case of needing to type in another window during a loading screen or whatnot, but my split key is E, and in the game I run, E is also one of the menu navigation keys (although unused in the run), so what I was trying to get it to do is respond to the global hotkey toggle such that I can leave livesplit open, and be able to use that menu navigation key between runs without splitting (when global hotkeys are disabled). My global hotkey toggle button is an extra mouse button, so I'm not going to be hitting that while trying to type (it's a non-issue for me, having the global hotkeys button ignore which window is focused)

**Comment by Dalet** [comment]
After trying it, adding a setting to toggle focused hotkeys along manual global hotkeys toggles sounds good. You're only able to disable focused hotkeys while in focus so you still can't have global hotkeys enabled while alt tabbed

**Comment by Dalet** [comment]
Available for testing in v1.1-alpha: https://github.com/Dalet/LiveSplit.FocusedHotkeys/releases/tag/v1.1-alpha
I want to redo the settings UI completely before releasing 1.1 to the public.

**Comment by Californ1a** [comment]
Sweet, that works great
